spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://3.1.2.222:3306/microservice_db
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          batch_size: 500000
          order_inserts: true
          order_updates: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    batch:
      jdbc:
        initialize-schema: always
  kafka:
    bootstrap-servers: ${ERP_ADSYS_KAFKA_SERVERS:172.20.10.3:9092}
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: earliest
      acks: -1
      retries: 1
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
  sql:
    init:
      encoding: UTF-8
server:
  port: 8103

eureka:
  client:
    service-url:
      defaultZone: ${USER_SERVICE_URL_DEFAULT:http://discovery-server-container:8100/eureka/}
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

sonar:
  host:
    url: http://192.168.56.1:9000
  projectKey: led
  login: sqa_21e4f9518a021e8213c8594b99c98e26ea0bfad0
